name: Deploy Azure Functions

on:
  push:
    branches:
      - main
    paths:
      - 'azure-functions/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: SAXTech-DocProcessor
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure-functions'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm install -g azure-functions-core-tools@4
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Print Function App URL'
      run: |
        echo "Azure Function App deployed successfully!"
        echo "Function App URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
        echo "New ProcessDocumentWithEmbeddings endpoint: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/ProcessDocumentWithEmbeddings"
