name: Deploy Azure Functions

on:
  push:
    branches:
      - main
    paths:
      - 'azure-functions/**'
      - '.github/workflows/deploy-azure-functions.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'SAXTech-DocProcessor'
  RESOURCE_GROUP: 'SAXTech-AI'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './azure-functions'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Summary'
      run: |
        echo "✅ Deployment complete!"
        echo "Function App URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
        echo ""
        echo "Note: App settings for AI features are already configured in Azure portal"
